### ISSUE TITLE
Dynamodb GetItem without context

### ISSUE THREAD

**Issue by davidhopkins** [aws/aws-xray-sdk-go#139]
I am attempting to do something like the following:
```go
sess := session.New()
dynamo := dynamodb.New(sess, &aws.Config{
  Region: aws.String("local"),
})

xray.AWS(dynamo.Client)

params := &dynamodb.GetItemInput{
  TableName:      aws.String("table"),
  Key: map[string]*dynamodb.AttributeValue{
    "key": &dynamodb.AttributeValue{S: aws.String("s")},
  },
}

dynamo.GetItem(params)
```
which results in the following panic:
```
panic: failed to begin subsegment named 'dynamodb': segment cannot be found.

goroutine 1 [running]:
github.com/aws/aws-xray-sdk-go/strategy/ctxmissing.(*DefaultRuntimeErrorStrategy).ContextMissing(0x176c860, 0xd0dac0, 0xc0002ee9b0)
  /home/david/gopath/pkg/mod/github.com/aws/aws-xray-sdk-go@v1.0.0-rc.13/strategy/ctxmissing/default_context_missing.go:45 +0x35
github.com/aws/aws-xray-sdk-go/xray.BeginSubsegment(0xfee040, 0xc000022110, 0xe29207, 0x8, 0x0, 0x0, 0x0)
  /home/david/gopath/pkg/mod/github.com/aws/aws-xray-sdk-go@v1.0.0-rc.13/xray/segment.go:177 +0x9e7
github.com/aws/aws-xray-sdk-go/xray.glob..func1(0xc000259200)
  /home/david/gopath/pkg/mod/github.com/aws/aws-xray-sdk-go@v1.0.0-rc.13/xray/aws.go:60 +0xb7
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc000259358, 0xc000259200)
  /home/david/gopath/pkg/mod/github.com/aws/aws-sdk-go@v1.17.12/aws/request/handlers.go:216 +0xf2
github.com/aws/aws-sdk-go/aws/request.(*Request).Build(0xc000259200, 0x0, 0x0)
  /home/david/gopath/pkg/mod/github.com/aws/aws-sdk-go@v1.17.12/aws/request/request.go:359 +0x88
github.com/aws/aws-sdk-go/aws/request.(*Request).Sign(0xc000259200, 0x0, 0x0)
  /home/david/gopath/pkg/mod/github.com/aws/aws-sdk-go@v1.17.12/aws/request/request.go:380 +0x37
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc000259200, 0x0, 0x0)
  /home/david/gopath/pkg/mod/github.com/aws/aws-sdk-go@v1.17.12/aws/request/request.go:475 +0x15c
github.com/aws/aws-sdk-go/service/dynamodb.(*DynamoDB).GetItem(0xc0001f7e80, 0xc000208a50, 0x0, 0x0, 0x0)
  /home/david/gopath/pkg/mod/github.com/aws/aws-sdk-go@v1.17.12/service/dynamodb/api.go:2309 +0x92
main.main()
```

Realise I can use `dynamo.GetItemWithContext` and avoid this problem but it's surprising I cannot make non-context calls, to avoid tracing, when I want to. To provide a bit more context, there is a large codebase, all sharing the same db client and we want to phase tracing in over time so it's undesirable to trace all calls right away.

Am I doing something wrong or is it the simply the case that once you wrap the dynamo client any non-context call will panic?

**Comment by luluzhao** [comment]
@davidhopkins , sorry for the late reply. In current design of AWS X-Ray SDK Go, we inject `segment/subsegment` information into `context` for propagation which means in order to create `subsegment`, sdk will try to find segment in the context. If it cannot find the segment, it will panic. 

There is a way to suppress panic which called `ContextMissingStrategy`. The way how it works is that it will log an error message instead of panicing the program. Here I attached the example about how to enable it.
```
	xray.Configure(xray.Config{
   		// ... other configurations you have
   		ContextMissingStrategy: ctxmissing.NewDefaultLogErrorStrategy(),
  	})
```
Please let me know whether it can solve your problem or not.

**Comment by davidhopkins** [comment]
Hey Lulu! Yes and no it solves it. The panic is gone but now the logs are obviously now full of errors.

It seems odd there are two versions of most API e.g. `GetX` and `GetXWithContext` but only one of them is successful. Do you think it should be possible make calls e.g. `GetItem` without the library attempting to find the segment at all?

**Comment by luluzhao** [comment]
@davidhopkins The `LogErrorContextMissingStrategy` is the way to catch the panic error and then log it instead of directly break the application. So yes, the logs will be full of errors.

 `aws-sdk-go` team designed two methods `GetX` and GetXWithContext` when they released v1 sdk and like I said in previous reply, `segment/subsegment` info is passed through `context`. There has to be a context to show up in order to enable tracing. If you don't need to trace AWS SDK calls and just want to make `GetItem` call, you can remove the X-Ray sdk client instrumentation and in this way, the library won't try to find the segment in order to create subsegment for aws sdk calls. If you need to trace `GetItem`, `context` has to be there. At least for using v1 aws go sdk. If in future, aws go sdk decides to merge these two methods together, we will support that.

**Comment by davidhopkins** [comment]
If the user story is that we want to instrument some call but not all is this the best way to do it? I am worried repeatedly/condtionally wrapping the dynamo client might be bad for performance etc.
```
dynamo := dynamodb.New...

fun getThing() {
   xray.AWS(dynamo.Client)
   dynamo.GetItemWithContext...
   ...
}

fun putThing() {
   dynamo.PutItem...
   ...
}
```

**Comment by luluzhao** [comment]
You don't need to repeatedly wrap dynamodb client. You only need to do it once. After wrapping the dynamodb client, customers need to call GetXWithContext in order for xray to generate subsegment.

**Comment by davidhopkins** [comment]
Thanks for the fast reply but I don't think you've understood my use-case fully. Specifically I need to be able to:

1. Call GetXWithContext
2. Call PutX (without context)

If I wrap the dynamodb client once then 2 will either panic or fill the logs with errors. I would like to avoid both of these and the only way I can see to achieve this is to conditionally wrap the client. Is conditionally wrapping/not wrapping the client OK to do from a performance perspective?

Thanks!

**Comment by luluzhao** [comment]
@davidhopkins Sorry I misunderstand your use case at beginning. Unfortunately, conditionally wrapping the client is the only way to do if you don't want to suppress the error by using context missing strategy as I mentioned before. It should be ok since SDK suppose to be very light from performance perspective when we design it.
