### ISSUE TITLE
stripPasswords("pwd=") makes infinite loop

### ISSUE THREAD

**Issue by shogo82148** [aws/aws-xray-sdk-go#181]
Test code:

```diff
diff --git a/xray/sql_test.go b/xray/sql_test.go
index 4680900..30cb509 100644
--- a/xray/sql_test.go
+++ b/xray/sql_test.go
@@ -163,7 +163,7 @@ func (s *sqlTestSuite) TestPasswordlessConnectionString() {
 }
 
 func (s *sqlTestSuite) TestPasswordConnectionString() {
-	s.mockDB("user=user password=password database=database")
+	s.mockDB("pwd=")
 	s.mockPSQL(nil)
 	s.connect()
 
```

Log:

```
Running tool: /usr/local/bin/go test -timeout 30s <long arguments omitted> -v -race

=== RUN   TestSQL
=== RUN   TestPasswordConnectionString
panic: test timed out after 30s

goroutine 21 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:1377 +0x11c
created by time.goFunc
	/usr/local/Cellar/go/1.13.6/libexec/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001ba000, 0x1a2d589, 0x7, 0x1a52818, 0x1)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:961 +0x68a
testing.runTests.func1(0xc0001ba000)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:1202 +0xa7
testing.tRunner(0xc0001ba000, 0xc00010bd10)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:909 +0x19a
testing.runTests(0xc00000ef60, 0x20a1f80, 0x2d, 0x2d, 0x0)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:1200 +0x522
testing.(*M).Run(0xc0000f4180, 0x0)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:1117 +0x300
github.com/aws/aws-xray-sdk-go/xray.TestMain(0xc0000f4180)
	/Users/shogoichinose/src/github.com/shogo82148/aws-xray-sdk-go/xray/util_test.go:30 +0x8b
main.main()
	_testmain.go:130 +0x224

goroutine 5 [chan receive]:
testing.(*T).Run(0xc0001ba200, 0x18f1736, 0x1c, 0xc000214690, 0x0)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:961 +0x68a
testing.runTests.func1(0xc0001ba200)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:1202 +0xa7
testing.tRunner(0xc0001ba200, 0xc0000a3cc8)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:909 +0x19a
testing.runTests(0x1a52a20, 0xc00000fc80, 0x1, 0x1, 0xc0000a3d50)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:1200 +0x522
testing.RunTests(0x1a52a20, 0xc00000fc80, 0x1, 0x1, 0x0)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:1175 +0x5e
github.com/stretchr/testify/suite.Run(0xc0001ba100, 0x1be2200, 0xc0000c65f0)
	/Users/shogoichinose/pkg/mod/github.com/stretchr/testify@v1.1.4/suite/suite.go:102 +0x5b9
github.com/aws/aws-xray-sdk-go/xray.TestSQL(0xc0001ba100)
	/Users/shogoichinose/src/github.com/shogo82148/aws-xray-sdk-go/xray/sql_test.go:21 +0xe2
testing.tRunner(0xc0001ba100, 0x1a52818)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:960 +0x652

goroutine 6 [runnable]:
bytes.(*Buffer).WriteByte(0xc0000a5760, 0x2b63d, 0xc000586000, 0x2b607)
	/usr/local/Cellar/go/1.13.6/libexec/src/bytes/buffer.go:263 +0x177
github.com/aws/aws-xray-sdk-go/xray.stripPasswords(0x1a2c721, 0x4, 0x1a2bda0, 0x1)
	/Users/shogoichinose/src/github.com/shogo82148/aws-xray-sdk-go/xray/sql.go:261 +0x26b
github.com/aws/aws-xray-sdk-go/xray.SQL(0x1a2d86f, 0x7, 0x1a2c721, 0x4, 0xc0001d2868, 0xc00026c038, 0xc0001fb6e0)
	/Users/shogoichinose/src/github.com/shogo82148/aws-xray-sdk-go/xray/sql.go:79 +0x1cb
github.com/aws/aws-xray-sdk-go/xray.(*sqlTestSuite).connect(0xc0000c65f0)
	/Users/shogoichinose/src/github.com/shogo82148/aws-xray-sdk-go/xray/sql_test.go:56 +0x7c
github.com/aws/aws-xray-sdk-go/xray.(*sqlTestSuite).TestPasswordConnectionString(0xc0000c65f0)
	/Users/shogoichinose/src/github.com/shogo82148/aws-xray-sdk-go/xray/sql_test.go:168 +0x90
reflect.Value.call(0xc000206360, 0xc0000105c0, 0x13, 0x1a2c4c1, 0x4, 0xc00005df10, 0x1, 0x1, 0xc0001d5270, 0x5861160, ...)
	/usr/local/Cellar/go/1.13.6/libexec/src/reflect/value.go:460 +0x62b
reflect.Value.Call(0xc000206360, 0xc0000105c0, 0x13, 0xc00004bf10, 0x1, 0x1, 0x20a8e40, 0xc00004bea8, 0x10875c2)
	/usr/local/Cellar/go/1.13.6/libexec/src/reflect/value.go:321 +0xd4
github.com/stretchr/testify/suite.Run.func2(0xc0001ba300)
	/Users/shogoichinose/pkg/mod/github.com/stretchr/testify@v1.1.4/suite/suite.go:95 +0x1e3
testing.tRunner(0xc0001ba300, 0xc000214690)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:960 +0x652

goroutine 7 [select]:
database/sql.(*DB).connectionOpener(0xc000266000, 0x1beac40, 0xc00008f1c0)
	/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:1052 +0x140
created by database/sql.OpenDB
	/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:722 +0x2b3

goroutine 8 [select]:
database/sql.(*DB).connectionResetter(0xc000266000, 0x1beac40, 0xc00008f1c0)
	/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:1065 +0x161
created by database/sql.OpenDB
	/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:723 +0x2e9

goroutine 9 [select]:
database/sql.(*DB).connectionOpener(0xc0002660c0, 0x1beac40, 0xc00008f200)
	/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:1052 +0x140
created by database/sql.OpenDB
	/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:722 +0x2b3

goroutine 10 [select]:
database/sql.(*DB).connectionResetter(0xc0002660c0, 0x1beac40, 0xc00008f200)
	/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:1065 +0x161
created by database/sql.OpenDB
	/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:723 +0x2e9
FAIL	github.com/aws/aws-xray-sdk-go/xray	30.349s
FAIL
Error: Tests failed.
```

**Comment by bhautikpip** [comment]
Hi @shogo82148,

Thanks for pointing out this issue. I was able to reproduce this. We might want to address this in go test cases fixing PR. I could come up with temporary work around.

```
case '=':
			tokStr := strings.ToLower(tok.String())
			if tokStr == `pwd==` || tokStr == `password==`{
				inBraces = false
				flush()
				return res.String()
			}
			isPassword = `password=` == tokStr || `pwd=` == tokStr
			if b, err := buf.ReadByte(); err == nil && b == '{' {
				inBraces = true
			}
			buf.UnreadByte() 
```
