### ISSUE TITLE
Tests Failing -- `TestBadRoundTripDial`

### ISSUE THREAD

**Issue by MLCarey321** [aws/aws-xray-sdk-go#471]
The following error is occurring when running `make test` locally:
```
--- FAIL: TestBadRoundTripDial (0.75s)
    client_test.go:392: 
        	Error Trace:	/Users/iuh483/repos/aws-xray-sdk-go/xray/client_test.go:392
        	Error:      	An error is expected but got nil.
        	Test:       	TestBadRoundTripDial
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x1015da690]

goroutine 511 [running]:
testing.tRunner.func1.2({0x101bad600, 0x102373e90})
	/opt/homebrew/Cellar/go/1.22.4/libexec/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.22.4/libexec/src/testing/testing.go:1634 +0x33c
panic({0x101bad600?, 0x102373e90?})
	/opt/homebrew/Cellar/go/1.22.4/libexec/src/runtime/panic.go:770 +0x124
github.com/aws/aws-xray-sdk-go/xray.TestBadRoundTripDial(0x140009881a0)
	/Users/iuh483/repos/aws-xray-sdk-go/xray/client_test.go:400 +0x310
testing.tRunner(0x140009881a0, 0x101cb8850)
	/opt/homebrew/Cellar/go/1.22.4/libexec/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 1
	/opt/homebrew/Cellar/go/1.22.4/libexec/src/testing/testing.go:1742 +0x318
FAIL	github.com/aws/aws-xray-sdk-go/xray	2.158s
FAIL
make: *** [test] Error 1
```

**Comment by MLCarey321** [comment]
I'm confused -- what exactly is the error that's expected? Right now, the test results in a 404 response with no error, which is actually what I'd expect given how the request is being built.
